version: "3.7"
services:
  db:
    image: arifh19/sipeka-db
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}

  redis:
    image: arifh19/sipeka-redis
    restart: always
    volumes:
      - ./redis:/data

  backend:
    image: arifh19/sipeka-backend
    ports:
      - "3000-3002:3000"
    depends_on:
      - db
      - redis
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - JWT_KEYS=${JWT_KEYS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MQTT=${MQTT}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "7000:80"
    environment:
      PMA_HOST: db
